services:
  - type: web
    name: zavian
    runtime: static
    buildCommand: ""
    staticPublishPath: ./digital
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
